name: Build

on:
  workflow_call:

jobs:
  build-push:
    name: Build & Push
    runs-on: ubuntu-latest 
    
    steps:
      - name: Build
        run: |
          echo build

      - name: Push
        run: |
          echo push
